apiVersion: apps/v1
kind: Deployment
metadata:
  name: insure-me-app
  labels:
    app: insure-me
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insure-me
  template:
    metadata:
      labels:
        app: insure-me
    spec:
      containers:
        - name: insure-me-container
          image: prmd77/insure-me:3.0
          ports:
            - containerPort: 8081
         
---
apiVersion: v1
kind: Service
metadata:
  name: insure-me-service
spec:
  selector:
    app: insure-me
  type: NodePort
  ports:
    - protocol: TCP
      port: 80        # Service port (ClusterIP)
      targetPort: 8081 # Maps to containerPort
      nodePort: 32040  # Exposed port on the node
